AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Parameters:
  BucketName:
    Type: String

Resources:
  FileStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedOrigins:
              - "*"
            AllowedMethods:
              - GET
              - POST

  LambdaIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                Resource: !Join ["", ["arn:aws:s3:::", !Ref BucketName, "/*"]]
          PolicyName: stellaris-save-converter

  UploadPresignFunction:
    Type: AWS::Serverless::Function
    DependsOn: LambdaIamRole
    Properties:
      CodeUri: presign/
      Handler: app.upload_lambda_handler
      Runtime: python3.6
      Role: !GetAtt LambdaIamRole.Arn
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          EXPIRATION: 60
      Events:
        Upload:
          Type: Api
          Properties:
            Path: /upload
            Method: get

  DownloadPresignFunction:
    Type: AWS::Serverless::Function
    DependsOn: LambdaIamRole
    Properties:
      CodeUri: presign/
      Handler: app.download_lambda_handler
      Runtime: python3.6
      Role: !GetAtt LambdaIamRole.Arn
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          EXPIRATION: 60
      Events:
        Upload:
          Type: Api
          Properties:
            Path: /download
            Method: get

  ConverterFunction:
    Type: AWS::Serverless::Function
    DependsOn: LambdaIamRole
    Properties:
      CodeUri: converter/
      Handler: app.lambda_handler
      Runtime: python3.6
      Role: !GetAtt LambdaIamRole.Arn
      MemorySize: 3008
      Timeout: 900
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
      Events:
        Converter:
          Type: S3
          Properties:
            Bucket: !Ref FileStorageBucket
            Events: "s3:ObjectCreated:*"
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: zip

Outputs:
  ApiRoot:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  FileStorageBucket:
    Description: "File S3 Bucket ARN"
    Value: !GetAtt FileStorageBucket.Arn
  FunctionIamRole:
    Description: "IAM role for functions"
    Value: !GetAtt LambdaIamRole.Arn
  UploadFunction:
    Description: "Upload Lambda Function ARN"
    Value: !GetAtt UploadPresignFunction.Arn
  DownloadFunction:
    Description: "Download Lambda Function ARN"
    Value: !GetAtt DownloadPresignFunction.Arn
  ConverterFunction:
    Description: "Converter Lambda Function ARN"
    Value: !GetAtt ConverterFunction.Arn
